### ISSUE TITLE
Speedsaver/ArduiPi_OLED@37230d8 may be too aggressive

### ISSUE THREAD

**Issue by peterbmckinley** [Speedsaver/ArduiPi_OLED#1]
I have noticed on the MangoPi-R3c image, which has the spam killing OLED fix, that fairly regularly the system boots, and the software loads and works, but there is no OLED display, OLED is blank.

I suspect that commit 37230d8, introduced to prevent "I2C write error : No such device or address" messages flooding the console when there is no OLED connected, is too aggressive and may be shutting down the OLED display inappropriately at times.

Is it possible to have the driver try to write to the display for say 5 seconds, before giving up and assuming no display is physically connected and killing the process?

**Comment by sc6502** [comment]
The write error spam is suppressed, but do you also see a "I2C ioctl error"?
This may appear when the device is opened.  Is this error observed in any failure cases?

Does the single "I2C write error" still say "No such device or address" or something else?

Is it possible to try it without the fix, say at commit df55a2ec ?
It would be useful to know whether the error is temporary (doesn't work initially, but then does work OK), intermittent (alternates between working and not working), or permanent (once broken, it never recovers).

**Comment by peterbmckinley** [comment]
Closing issue as it's been decided to revert the anti spamming fix
